### PR TITLE
Added correct closingDistanceRelative for Czech leagues

### PR DESCRIPTION
**Pull request by vrka**
Hi Victor, 
recently the flyxc.app started to show wrong closing circle for Czech leagues. I suspect that the default value for closing was changed and there is not set the value in definition of Czech leagues.

Here's a PR stating the correct value of 5% for all the triangles.

Karel

## Summary by Sourcery

This pull request fixes the incorrect closing circle distance for Czech leagues by setting the closingDistanceRelative value to 5% for all triangle types in the scoring rules.

- **Bug Fixes**:
    - Corrected the closing distance relative value for Czech leagues to 5% for all triangle types.

## Summary by CodeRabbit

- **New Features**
	- Improved scoring rules for triangle categories with a new `closingDistanceRelative` parameter.
- **Enhancements**
	- Adjusted scoring multipliers for `freeTriangle` and `faiTriangle` under various rule sets for better accuracy.

### CODE REVIEW

**Comment by vicb** [comment]
Thanks for the PR!

Do you have a link to the rules?

It would be nice to add some tests, maybe @flyingtof can help with that if you need (he rewrote the scoring recently).

**Comment by vrka** [comment]
https://www.xcontest.org/cesko/pravidla/

in Czech

**Comment by vicb** [comment]
@vrka could you please 
- add the link to the rule as a comment in the source code*
- add yourself as a contributor in the `README.md` and `about-modal.ts`

To create a test case (if you have a local version working):
- draw a triangle trigerring the issue on flyxc.app
- make sure the issue is fixed on your local version (copy the query params to your local version)
- use [this decoder](https://developers.google.com/maps/documentation/utilities/polylineutility) to get the point location to write your test case.

It seems like cloudflare does not support creating deployments for PRs but using `npm i && nx dev` should be enough to test that locally (feel free to update `CONTRIBUTING.md` if that works).

Thanks

**Comment by vrka** [comment]
I' ve added rules reference to source. I added 3 simple test that check the closing distance (failing for 20% that were before and passing now for 5%)

I do not feel it is necessary to add me to the contributors ( maybe when/if I add something more ;-)

**Review by vicb — APPROVED** [review]
Looks good, thanks!
I'll add you to the contribs - I need to update the READMEs

**Pull request merged**
